#Step 1
#https://www.youtube.com/watch?v=-pTel5FojAQ&ab_channel=Codeching
FROM node:20-alpine3.16 as builder
WORKDIR /app
COPY package.json ./
RUN npm i
COPY . .
CMD ["npm", "run", "build"]

#Step 2 server side render
FROM nginx:1.19.0
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
