apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-microservices
data:
  POST_PORT: "4000"
  POST_TOPIC: "PostCreated"
  COMMENT_PORT: "5000"
  COMMENT_TOPIC: "CommentCreated"
  QUERY_PORT: "6000"
  KAFKA_BROKERS: "my-release-kafka:9092"
  KAFKA_TOPICS: "PostCreated"
  KAFKA_REPLICATION_FACTOR: "3"
  KAFKA_NUM_PARTITIONS: "4"
