version: '3.9'

services:

  client:
   container_name: client
   image: alazidis/blog-microservices-client   
   expose: 
    - ${REACT_APP_PORT} 
   ports:
     - "${REACT_APP_PORT}:${REACT_APP_PORT}"
   stdin_open: true
   environment:
    REACT_APP_POST_HOST: ${REACT_APP_POST_HOST}
    REACT_APP_COMMENT_HOST: ${REACT_APP_COMMENT_HOST}
    REACT_APP_QUERY_HOST: ${REACT_APP_QUERY_HOST}
    CHOKIDAR_USEPOLLING: true
   volumes:
    - ./client/:/app/
    - /app/node_modules

  nginx:
   build:
    dockerfile: ./Dockerfile.dev
    context: ./nginx
   restart: always
   ports:
    - "3050:80"
   depends_on:
    - client
    - posts
    - comments
    - query-comments-post

  comments:
    container_name: comments
    image: alazidis/blog-microservices-comments
    ports:
     - "${COMMENT_PORT}:${COMMENT_PORT}"
    environment:
      COMMENT_PORT: ${COMMENT_PORT}
      COMMENT_TOPIC: ${COMMENT_TOPIC}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    networks:
      - default
    depends_on:
      - kafka_admin
    restart: always
  
  posts:
    container_name: posts
    image: alazidis/blog-microservices-posts
    ports:
     - "${POST_PORT}:${POST_PORT}"
    environment:
      POST_PORT: ${POST_PORT}
      POST_TOPIC: ${POST_TOPIC}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    networks:
      - default
    depends_on:
      - kafka_admin
    restart: always
  
  query-comments-post:
    container_name: query-comments-post
    image: alazidis/blog-microservices-query
    ports:
     - "${QUERY_PORT}:${QUERY_PORT}"
    environment:
     QUERY_PORT: ${QUERY_PORT}
     POST_TOPIC: ${POST_TOPIC}
     COMMENT_TOPIC: ${COMMENT_TOPIC}
     KAFKA_BROKERS: ${KAFKA_BROKERS}
    restart: always
    depends_on:
      - kafka_admin
    networks:
     - default
    
  
  kafka_admin:
   container_name: kafka_admin
   image: alazidis/kafka_admin_client
   environment:
    KAFKA_TOPICS: ${KAFKA_TOPICS}
    KAFKA_BROKERS: ${KAFKA_BROKERS}
    KAFKA_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
    KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
   restart: always
   networks:
     - default
   depends_on:
     control-center:
       condition: service_started       
   

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
    - default

  kafka1:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka1
    ports:
      - "8097:8097"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8097,INTERNAL://kafka1:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
     - default
    restart: on-failure
    healthcheck:
        test: ["CMD", "ping", "-c","1", "localhost:8098"]
        interval: 30s
        timeout: 10s
        retries: 5

  kafka2:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka2
    ports:
      - "8098:8098"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8098,INTERNAL://kafka2:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
     - default
    restart: on-failure
    healthcheck:
        test: ["CMD", "ping", "-c","1", "localhost:8098"]
        interval: 30s
        timeout: 10s
        retries: 5

  kafka3:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka3
    ports:
      - "8099:8099"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8099,INTERNAL://kafka3:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
     - default
    restart: on-failure
    healthcheck:
        test: ["CMD", "ping", "-c","1", "localhost:8098"]
        interval: 30s
        timeout: 10s
        retries: 5
  
  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    depends_on:
      - kafka1
      - kafka2
      - kafka3 
    ports:
      - "9021:9021"
    expose:
      - 9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka1:19092,kafka2:29092,kafka3:39092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
    networks:
    - default
    restart: always

networks:
    default:
     driver: bridge